export const COUNTRIES = [
  {
    id: 'germany',
    name: 'Germany',
    flag: '🇩🇪',
    tagline: 'Tuition-Free Public Universities',
    headerColor: '#142d6e',
    accentColor: '#3b7de0',
    badgeColor: '#dbeafe',
    badgeText: '#1a3a8c',
    highlights: [
      'APS Certificate required',
      'Uni-Assist applications',
      'Blocked account €11,208/yr',
      'Student visa ~6 weeks',
    ],
    intake: 'Winter & Summer',
    costRange: '€800–€1,200/mo',
    costINR: '≈ ₹72K–1.08L/mo',
    topUnis: ['TU Munich', 'RWTH Aachen', 'TU Berlin', 'KIT'],
    visaType: 'National Visa Type D',
    workAllowed: '120 days/year',
    postStudy: '18-month Job Seeker Visa',
    popular: true,
  },
  {
    id: 'usa',
    name: 'United States',
    flag: '🇺🇸',
    tagline: 'World-Ranked Research Programs',
    headerColor: '#7f1d1d',
    accentColor: '#ef4444',
    badgeColor: '#fee2e2',
    badgeText: '#991b1b',
    highlights: [
      'GRE/GMAT required',
      'Direct university portals',
      'F-1 Visa + SEVIS $350',
      'OPT 1yr + STEM 2yr',
    ],
    intake: 'Fall & Spring',
    costRange: '$1,500–$2,500/mo',
    costINR: '≈ ₹1.26L–2.1L/mo',
    topUnis: ['MIT', 'Stanford', 'CMU', 'Georgia Tech'],
    visaType: 'F-1 Student Visa',
    workAllowed: '20 hrs/week on-campus',
    postStudy: 'OPT 3 years (STEM)',
    popular: true,
  },
  {
    id: 'canada',
    name: 'Canada',
    flag: '🇨🇦',
    tagline: 'Best PR Pathway for Indians',
    headerColor: '#7c2d12',
    accentColor: '#f97316',
    badgeColor: '#fed7aa',
    badgeText: '#9a3412',
    highlights: [
      'IELTS 6.5+ required',
      'SDS = 2-week permit',
      'PGWP up to 3 years',
      'PR via Express Entry',
    ],
    intake: 'Sept & January',
    costRange: 'CAD 1,600–2,500/mo',
    costINR: '≈ ₹97K–1.53L/mo',
    topUnis: ['UofT', 'UBC', 'Waterloo', 'McGill'],
    visaType: 'Study Permit (SDS)',
    workAllowed: '20 hrs/week off-campus',
    postStudy: 'PGWP 3 yrs → PR',
    popular: true,
  },
  {
    id: 'uk',
    name: 'United Kingdom',
    flag: '🇬🇧',
    tagline: '1-Year Masters + Graduate Visa',
    headerColor: '#1e3a5f',
    accentColor: '#3b82f6',
    badgeColor: '#dbeafe',
    badgeText: '#1e40af',
    highlights: [
      'IELTS 6.5+ required',
      'CAS from university',
      'Student Visa (Tier 4)',
      'Graduate Route: 2 years',
    ],
    intake: 'September & January',
    costRange: '£1,200–£2,000/mo',
    costINR: '≈ ₹1.27L–2.12L/mo',
    topUnis: ['Oxford', 'Cambridge', 'UCL', 'Imperial'],
    visaType: 'Student Visa (Tier 4)',
    workAllowed: '20 hrs/week',
    postStudy: 'Graduate Route 2 years',
    popular: false,
  },
  {
    id: 'australia',
    name: 'Australia',
    flag: '🇦🇺',
    tagline: 'Post-Study Work Rights 2–4 Years',
    headerColor: '#064e3b',
    accentColor: '#10b981',
    badgeColor: '#d1fae5',
    badgeText: '#065f46',
    highlights: [
      'IELTS 6.0–6.5 required',
      'Student Visa Subclass 500',
      'Post-Study Work 2–4 yrs',
      'PR via 189/190 pathway',
    ],
    intake: 'Feb & July',
    costRange: 'AUD 2,000–3,000/mo',
    costINR: '≈ ₹1.09L–1.63L/mo',
    topUnis: ['Melbourne', 'ANU', 'Sydney', 'UNSW'],
    visaType: 'Student Visa 500',
    workAllowed: '48 hrs/fortnight',
    postStudy: 'TSS → PR pathway',
    popular: false,
  },
]

export const getCountryByName = (name) =>
  COUNTRIES.find(c => c.name.toLowerCase().includes(name.toLowerCase()))